#!/bin/bash

rm -r small-images
mkdir small-images

header() {
  convert images/$1 -quality 0.95 -resize 1920x664\> \
          small-images/${1%.*}.jpg
  echo header $1
}

small() {
  convert images/$1 -quality 0.95 -resize 600x600\> \
          small-images/${1%.*}.jpg
  echo small $1
}

header header-datasci.jpg
header header-compsci.jpg
header header-linux.jpg
header header-research.png
header header-hardware.jpg

for f in `ls images | grep -v ^header-`; do
  small $f
done
